window.LINA_ORG_UNITS = [
  {
    "id": "CEO",
    "name": "CEO",
    "level": "company",
    "orgType": "CEO",
    "orgDepth": 0,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": null,
    "members": 14,
    "readiness": 83,
    "trust": 59,
    "fatigue": 57,
    "engagement": 62,
    "risk": "medium",
    "ambassadors": 0,
    "tags": [
      "조직 연결 허브",
      "변화 수용 높음",
      "리더 정보 확인 필요"
    ],
    "recommendation": "CEO은 업로드된 조직 마스터 기준의 CEO 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "STRATEGY",
    "name": "경영전략부문",
    "level": "division",
    "orgType": "부문",
    "orgDepth": 1,
    "leader": "박경식",
    "leaderTitle": "전무",
    "parentId": "CEO",
    "members": 3,
    "readiness": 61,
    "trust": 70,
    "fatigue": 49,
    "engagement": 61,
    "risk": "low",
    "ambassadors": 2,
    "tags": [
      "신뢰 안정"
    ],
    "recommendation": "경영전략부문은 업로드된 조직 마스터 기준의 부문 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "DIGITAL",
    "name": "Digital부문",
    "level": "division",
    "orgType": "부문",
    "orgDepth": 1,
    "leader": "이진호",
    "leaderTitle": "부사장",
    "parentId": "CEO",
    "members": 3,
    "readiness": 63,
    "trust": 68,
    "fatigue": 51,
    "engagement": 60,
    "risk": "low",
    "ambassadors": 2,
    "tags": [
      "기본 모니터링"
    ],
    "recommendation": "Digital부문은 업로드된 조직 마스터 기준의 부문 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Digital부문",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "DT",
    "name": "DT부문",
    "level": "division",
    "orgType": "부문",
    "orgDepth": 1,
    "leader": "김호섭",
    "leaderTitle": "부사장",
    "parentId": "CEO",
    "members": 4,
    "readiness": 73,
    "trust": 64,
    "fatigue": 60,
    "engagement": 59,
    "risk": "medium",
    "ambassadors": 4,
    "tags": [
      "조직 연결 허브",
      "변화 수용 높음"
    ],
    "recommendation": "DT부문은 업로드된 조직 마스터 기준의 부문 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "OPERATION",
    "name": "Operation본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 1,
    "leader": "허혁",
    "leaderTitle": "이사",
    "parentId": "CEO",
    "members": 5,
    "readiness": 60,
    "trust": 57,
    "fatigue": 59,
    "engagement": 53,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "조직 연결 허브"
    ],
    "recommendation": "Operation본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Operation본부",
    "status": "active",
    "sortOrder": 4
  },
  {
    "id": "FINANCE",
    "name": "Finance부문",
    "level": "division",
    "orgType": "부문",
    "orgDepth": 1,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CEO",
    "members": 2,
    "readiness": 66,
    "trust": 73,
    "fatigue": 42,
    "engagement": 66,
    "risk": "low",
    "ambassadors": 2,
    "tags": [
      "신뢰 안정",
      "리더 정보 확인 필요"
    ],
    "recommendation": "Finance부문은 업로드된 조직 마스터 기준의 부문 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Finance부문",
    "status": "active",
    "sortOrder": 5
  },
  {
    "id": "FACE_SALES",
    "name": "대면영업부문",
    "level": "division",
    "orgType": "부문",
    "orgDepth": 1,
    "leader": "이장록",
    "leaderTitle": "전무",
    "parentId": "CEO",
    "members": 3,
    "readiness": 80,
    "trust": 53,
    "fatigue": 44,
    "engagement": 63,
    "risk": "medium",
    "ambassadors": 4,
    "tags": [
      "변화 수용 높음"
    ],
    "recommendation": "대면영업부문은 업로드된 조직 마스터 기준의 부문 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문",
    "status": "active",
    "sortOrder": 6
  },
  {
    "id": "HR",
    "name": "인사관리부문",
    "level": "division",
    "orgType": "부문",
    "orgDepth": 1,
    "leader": "박규현",
    "leaderTitle": "전무",
    "parentId": "CEO",
    "members": 4,
    "readiness": 77,
    "trust": 64,
    "fatigue": 60,
    "engagement": 60,
    "risk": "medium",
    "ambassadors": 4,
    "tags": [
      "조직 연결 허브",
      "변화 수용 높음"
    ],
    "recommendation": "인사관리부문은 업로드된 조직 마스터 기준의 부문 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 인사관리부문",
    "status": "active",
    "sortOrder": 7
  },
  {
    "id": "LEGAL_COMPLIANCE",
    "name": "법무&준법감시부문",
    "level": "division",
    "orgType": "부문",
    "orgDepth": 1,
    "leader": "이재현",
    "leaderTitle": "전무",
    "parentId": "CEO",
    "members": 2,
    "readiness": 61,
    "trust": 75,
    "fatigue": 54,
    "engagement": 61,
    "risk": "low",
    "ambassadors": 1,
    "tags": [
      "신뢰 안정"
    ],
    "recommendation": "법무&준법감시부문은 업로드된 조직 마스터 기준의 부문 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 법무&준법감시부문",
    "status": "active",
    "sortOrder": 8
  },
  {
    "id": "AUDIT_EXECUTIVE",
    "name": "최고감사책임자",
    "level": "hq",
    "orgType": "책임자",
    "orgDepth": 1,
    "leader": "채명균",
    "leaderTitle": "전무",
    "parentId": "CEO",
    "members": 1,
    "readiness": 55,
    "trust": 54,
    "fatigue": 50,
    "engagement": 53,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "특수 조직"
    ],
    "recommendation": "최고감사책임자은 업로드된 조직 마스터 기준의 책임자 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 최고감사책임자",
    "status": "active",
    "sortOrder": 9
  },
  {
    "id": "RM",
    "name": "RM본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 1,
    "leader": "오수연",
    "leaderTitle": "상무",
    "parentId": "CEO",
    "members": 2,
    "readiness": 60,
    "trust": 66,
    "fatigue": 61,
    "engagement": 55,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "기본 모니터링"
    ],
    "recommendation": "RM본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > RM본부",
    "status": "active",
    "sortOrder": 10
  },
  {
    "id": "EXTERNAL_COOPERATION",
    "name": "대외협력본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 1,
    "leader": "김기성",
    "leaderTitle": "부사장",
    "parentId": "CEO",
    "members": 1,
    "readiness": 72,
    "trust": 55,
    "fatigue": 48,
    "engagement": 60,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "변화 수용 높음"
    ],
    "recommendation": "대외협력본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대외협력본부",
    "status": "active",
    "sortOrder": 11
  },
  {
    "id": "CONSUMER_PROTECTION",
    "name": "소비자보호본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 1,
    "leader": "서민호",
    "leaderTitle": "상무",
    "parentId": "CEO",
    "members": 3,
    "readiness": 61,
    "trust": 70,
    "fatigue": 44,
    "engagement": 62,
    "risk": "low",
    "ambassadors": 2,
    "tags": [
      "신뢰 안정"
    ],
    "recommendation": "소비자보호본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 소비자보호본부",
    "status": "active",
    "sortOrder": 12
  },
  {
    "id": "LINAWON",
    "name": "라이나원",
    "level": "division",
    "orgType": "기타조직",
    "orgDepth": 1,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CEO",
    "members": 0,
    "readiness": 72,
    "trust": 52,
    "fatigue": 65,
    "engagement": 53,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "변화 수용 높음",
      "리더 정보 확인 필요",
      "특수 조직"
    ],
    "recommendation": "라이나원은 업로드된 조직 마스터 기준의 기타조직 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 라이나원",
    "status": "active",
    "sortOrder": 13
  },
  {
    "id": "TM_SALES",
    "name": "TM영업부문",
    "level": "division",
    "orgType": "부문",
    "orgDepth": 1,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CEO",
    "members": 0,
    "readiness": 76,
    "trust": 69,
    "fatigue": 48,
    "engagement": 66,
    "risk": "low",
    "ambassadors": 3,
    "tags": [
      "변화 수용 높음",
      "리더 정보 확인 필요"
    ],
    "recommendation": "TM영업부문은 업로드된 조직 마스터 기준의 부문 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > TM영업부문",
    "status": "active",
    "sortOrder": 14
  },
  {
    "id": "STRATEGY_MGMT",
    "name": "경영관리본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "임승관",
    "leaderTitle": "이사",
    "parentId": "STRATEGY",
    "members": 4,
    "readiness": 65,
    "trust": 59,
    "fatigue": 48,
    "engagement": 59,
    "risk": "medium",
    "ambassadors": 3,
    "tags": [
      "조직 연결 허브"
    ],
    "recommendation": "경영관리본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 경영관리본부",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "STRATEGY_MGMT_TEAM",
    "name": "경영관리팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "STRATEGY_MGMT",
    "members": 0,
    "readiness": 74,
    "trust": 59,
    "fatigue": 54,
    "engagement": 60,
    "risk": "medium",
    "ambassadors": 3,
    "tags": [
      "변화 수용 높음",
      "리더 정보 확인 필요"
    ],
    "recommendation": "경영관리팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 경영관리본부 > 경영관리팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "BRAND_EXPERIENCE",
    "name": "brand Experience팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "STRATEGY_MGMT",
    "members": 0,
    "readiness": 66,
    "trust": 57,
    "fatigue": 74,
    "engagement": 50,
    "risk": "high",
    "ambassadors": 2,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "brand Experience팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 경영관리본부 > brand Experience팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "MARKETING_STRATEGY",
    "name": "마케팅전략팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "STRATEGY_MGMT",
    "members": 0,
    "readiness": 63,
    "trust": 71,
    "fatigue": 48,
    "engagement": 62,
    "risk": "low",
    "ambassadors": 1,
    "tags": [
      "신뢰 안정",
      "리더 정보 확인 필요"
    ],
    "recommendation": "마케팅전략팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 경영관리본부 > 마케팅전략팀",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "PURCHASE",
    "name": "구매팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "STRATEGY_MGMT",
    "members": 0,
    "readiness": 53,
    "trust": 52,
    "fatigue": 67,
    "engagement": 46,
    "risk": "medium",
    "ambassadors": 0,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "구매팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 경영관리본부 > 구매팀",
    "status": "active",
    "sortOrder": 4
  },
  {
    "id": "CUSTOMER_SOLUTION",
    "name": "고객솔루션본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "도기철",
    "leaderTitle": "이사",
    "parentId": "STRATEGY",
    "members": 6,
    "readiness": 73,
    "trust": 68,
    "fatigue": 54,
    "engagement": 62,
    "risk": "low",
    "ambassadors": 4,
    "tags": [
      "조직 연결 허브",
      "변화 수용 높음"
    ],
    "recommendation": "고객솔루션본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 고객솔루션본부",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "CHANNEL_SOLUTION",
    "name": "채널전략솔루션팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CUSTOMER_SOLUTION",
    "members": 0,
    "readiness": 53,
    "trust": 55,
    "fatigue": 49,
    "engagement": 53,
    "risk": "medium",
    "ambassadors": 0,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "채널전략솔루션팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 고객솔루션본부 > 채널전략솔루션팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "NEW_GROWTH_SOLUTION",
    "name": "신성장솔루션팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CUSTOMER_SOLUTION",
    "members": 0,
    "readiness": 72,
    "trust": 57,
    "fatigue": 69,
    "engagement": 53,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "변화 수용 높음",
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "신성장솔루션팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 고객솔루션본부 > 신성장솔루션팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "SYNERGY_SOLUTION",
    "name": "시너지솔루션팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CUSTOMER_SOLUTION",
    "members": 0,
    "readiness": 66,
    "trust": 65,
    "fatigue": 75,
    "engagement": 52,
    "risk": "high",
    "ambassadors": 2,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "시너지솔루션팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 고객솔루션본부 > 시너지솔루션팀",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "HEALTH_SOLUTION",
    "name": "헬스솔루션팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CUSTOMER_SOLUTION",
    "members": 0,
    "readiness": 69,
    "trust": 71,
    "fatigue": 76,
    "engagement": 55,
    "risk": "high",
    "ambassadors": 2,
    "tags": [
      "신뢰 안정",
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "헬스솔루션팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 고객솔루션본부 > 헬스솔루션팀",
    "status": "active",
    "sortOrder": 4
  },
  {
    "id": "PRICING_OPTIMIZATION",
    "name": "Pricing 최적화팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CUSTOMER_SOLUTION",
    "members": 0,
    "readiness": 56,
    "trust": 53,
    "fatigue": 75,
    "engagement": 45,
    "risk": "high",
    "ambassadors": 1,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "Pricing 최적화팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 고객솔루션본부 > Pricing 최적화팀",
    "status": "active",
    "sortOrder": 5
  },
  {
    "id": "UW",
    "name": "UW팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CUSTOMER_SOLUTION",
    "members": 0,
    "readiness": 53,
    "trust": 50,
    "fatigue": 71,
    "engagement": 44,
    "risk": "high",
    "ambassadors": 0,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "UW팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 고객솔루션본부 > UW팀",
    "status": "active",
    "sortOrder": 6
  },
  {
    "id": "CHANNEL_STRATEGY",
    "name": "채널전략본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "최상혁",
    "leaderTitle": "이사",
    "parentId": "STRATEGY",
    "members": 5,
    "readiness": 66,
    "trust": 51,
    "fatigue": 63,
    "engagement": 51,
    "risk": "high",
    "ambassadors": 3,
    "tags": [
      "조직 연결 허브"
    ],
    "recommendation": "채널전략본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 채널전략본부",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "CHANNEL_PLANNING",
    "name": "채널기획팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CHANNEL_STRATEGY",
    "members": 0,
    "readiness": 60,
    "trust": 67,
    "fatigue": 60,
    "engagement": 56,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "채널기획팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 채널전략본부 > 채널기획팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "CHANNEL_OPERATION",
    "name": "채널운영팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CHANNEL_STRATEGY",
    "members": 0,
    "readiness": 52,
    "trust": 64,
    "fatigue": 61,
    "engagement": 52,
    "risk": "medium",
    "ambassadors": 0,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "채널운영팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 채널전략본부 > 채널운영팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "PARTNERSHIP_MANAGEMENT",
    "name": "제휴관리팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CHANNEL_STRATEGY",
    "members": 0,
    "readiness": 58,
    "trust": 58,
    "fatigue": 50,
    "engagement": 55,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "제휴관리팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 채널전략본부 > 제휴관리팀",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "MEDIA_BUSINESS",
    "name": "미디어사업팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CHANNEL_STRATEGY",
    "members": 0,
    "readiness": 61,
    "trust": 67,
    "fatigue": 52,
    "engagement": 59,
    "risk": "low",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "미디어사업팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 채널전략본부 > 미디어사업팀",
    "status": "active",
    "sortOrder": 4
  },
  {
    "id": "CHANNEL_PLANNING_SUPPORT",
    "name": "채널기획지원",
    "level": "team",
    "orgType": "지원조직",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CHANNEL_STRATEGY",
    "members": 0,
    "readiness": 65,
    "trust": 63,
    "fatigue": 72,
    "engagement": 52,
    "risk": "high",
    "ambassadors": 2,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "채널기획지원은 업로드된 조직 마스터 기준의 지원조직 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 경영전략부문 > 채널전략본부 > 채널기획지원",
    "status": "active",
    "sortOrder": 5
  },
  {
    "id": "DATA_CONTROL",
    "name": "Data Control본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "오인정",
    "leaderTitle": "이사",
    "parentId": "DIGITAL",
    "members": 3,
    "readiness": 70,
    "trust": 60,
    "fatigue": 48,
    "engagement": 61,
    "risk": "low",
    "ambassadors": 3,
    "tags": [
      "기본 모니터링"
    ],
    "recommendation": "Data Control본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Digital부문 > Data Control본부",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "DATA_STRATEGY",
    "name": "데이터전략팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "DATA_CONTROL",
    "members": 0,
    "readiness": 53,
    "trust": 51,
    "fatigue": 66,
    "engagement": 46,
    "risk": "high",
    "ambassadors": 0,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "데이터전략팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Digital부문 > Data Control본부 > 데이터전략팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "DATA_INSIGHT",
    "name": "데이터인사이트팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "DATA_CONTROL",
    "members": 0,
    "readiness": 72,
    "trust": 54,
    "fatigue": 68,
    "engagement": 53,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "변화 수용 높음",
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "데이터인사이트팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Digital부문 > Data Control본부 > 데이터인사이트팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "DATA_PLATFORM",
    "name": "데이터플랫폼팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "DATA_CONTROL",
    "members": 0,
    "readiness": 57,
    "trust": 51,
    "fatigue": 55,
    "engagement": 51,
    "risk": "high",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "데이터플랫폼팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Digital부문 > Data Control본부 > 데이터플랫폼팀",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "DIGITAL_SALES",
    "name": "Digital Sales본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "장재원",
    "leaderTitle": "상무",
    "parentId": "DIGITAL",
    "members": 2,
    "readiness": 77,
    "trust": 59,
    "fatigue": 45,
    "engagement": 64,
    "risk": "medium",
    "ambassadors": 3,
    "tags": [
      "변화 수용 높음"
    ],
    "recommendation": "Digital Sales본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Digital부문 > Digital Sales본부",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "DIGITAL_BUSINESS",
    "name": "디지털사업팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "DIGITAL_SALES",
    "members": 0,
    "readiness": 57,
    "trust": 69,
    "fatigue": 64,
    "engagement": 54,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "디지털사업팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Digital부문 > Digital Sales본부 > 디지털사업팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "DIGITAL_SALES_TEAM",
    "name": "디지털세일즈팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "DIGITAL_SALES",
    "members": 0,
    "readiness": 63,
    "trust": 59,
    "fatigue": 51,
    "engagement": 57,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "디지털세일즈팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Digital부문 > Digital Sales본부 > 디지털세일즈팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "DIGITAL_SERVICE",
    "name": "Digital Service본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "박기홍",
    "leaderTitle": "상무",
    "parentId": "DIGITAL",
    "members": 2,
    "readiness": 61,
    "trust": 71,
    "fatigue": 58,
    "engagement": 58,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "신뢰 안정"
    ],
    "recommendation": "Digital Service본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Digital부문 > Digital Service본부",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "DIGITAL_PRODUCT",
    "name": "디지털프로덕트팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "DIGITAL_SERVICE",
    "members": 0,
    "readiness": 74,
    "trust": 51,
    "fatigue": 56,
    "engagement": 56,
    "risk": "high",
    "ambassadors": 3,
    "tags": [
      "변화 수용 높음",
      "리더 정보 확인 필요"
    ],
    "recommendation": "디지털프로덕트팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Digital부문 > Digital Service본부 > 디지털프로덕트팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "DIGITAL_PLATFORM_SERVICE",
    "name": "디지털플랫폼팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "DIGITAL_SERVICE",
    "members": 0,
    "readiness": 55,
    "trust": 69,
    "fatigue": 58,
    "engagement": 55,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "디지털플랫폼팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Digital부문 > Digital Service본부 > 디지털플랫폼팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "INSURANCE_DEV",
    "name": "보험개발본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "김현우",
    "leaderTitle": "상무",
    "parentId": "DT",
    "members": 3,
    "readiness": 66,
    "trust": 67,
    "fatigue": 48,
    "engagement": 62,
    "risk": "low",
    "ambassadors": 3,
    "tags": [
      "기본 모니터링"
    ],
    "recommendation": "보험개발본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > 보험개발본부",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "DT_PLANNING",
    "name": "DT기획팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "INSURANCE_DEV",
    "members": 0,
    "readiness": 66,
    "trust": 68,
    "fatigue": 55,
    "engagement": 60,
    "risk": "low",
    "ambassadors": 2,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "DT기획팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > 보험개발본부 > DT기획팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "FINANCE_ACTUARY_DEV",
    "name": "재무/계리개발팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "INSURANCE_DEV",
    "members": 0,
    "readiness": 74,
    "trust": 66,
    "fatigue": 68,
    "engagement": 57,
    "risk": "medium",
    "ambassadors": 3,
    "tags": [
      "변화 수용 높음",
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "재무/계리개발팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > 보험개발본부 > 재무/계리개발팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "PRODUCT_CONTRACT_DEV",
    "name": "상품/계약개발팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "INSURANCE_DEV",
    "members": 0,
    "readiness": 60,
    "trust": 64,
    "fatigue": 50,
    "engagement": 58,
    "risk": "low",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "상품/계약개발팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > 보험개발본부 > 상품/계약개발팀",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "SALES_DEV",
    "name": "Sales개발본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "송유종",
    "leaderTitle": "이사",
    "parentId": "DT",
    "members": 2,
    "readiness": 71,
    "trust": 69,
    "fatigue": 68,
    "engagement": 57,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "피로도 관찰"
    ],
    "recommendation": "Sales개발본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > Sales개발본부",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "SALES_DEV_PLANNING",
    "name": "Sales개발기획팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "SALES_DEV",
    "members": 0,
    "readiness": 51,
    "trust": 62,
    "fatigue": 52,
    "engagement": 54,
    "risk": "medium",
    "ambassadors": 0,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "Sales개발기획팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > Sales개발본부 > Sales개발기획팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "SALES_DEV_TEAM",
    "name": "Sales개발팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "SALES_DEV",
    "members": 0,
    "readiness": 72,
    "trust": 69,
    "fatigue": 53,
    "engagement": 63,
    "risk": "low",
    "ambassadors": 2,
    "tags": [
      "변화 수용 높음",
      "리더 정보 확인 필요"
    ],
    "recommendation": "Sales개발팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > Sales개발본부 > Sales개발팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "INFRA_SERVICE",
    "name": "인프라서비스본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "서용식",
    "leaderTitle": "상무",
    "parentId": "DT",
    "members": 2,
    "readiness": 60,
    "trust": 51,
    "fatigue": 71,
    "engagement": 47,
    "risk": "high",
    "ambassadors": 1,
    "tags": [
      "피로도 관찰"
    ],
    "recommendation": "인프라서비스본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > 인프라서비스본부",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "INFRA_ENGINEERING",
    "name": "인프라인지니어링팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "INFRA_SERVICE",
    "members": 0,
    "readiness": 67,
    "trust": 59,
    "fatigue": 56,
    "engagement": 57,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "인프라인지니어링팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > 인프라서비스본부 > 인프라인지니어링팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "PLATFORM_ENGINEERING",
    "name": "플랫폼엔지니어링팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "INFRA_SERVICE",
    "members": 0,
    "readiness": 60,
    "trust": 54,
    "fatigue": 51,
    "engagement": 54,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "플랫폼엔지니어링팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > 인프라서비스본부 > 플랫폼엔지니어링팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "CISO",
    "name": "CISO본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "조용현",
    "leaderTitle": "상무",
    "parentId": "DT",
    "members": 1,
    "readiness": 60,
    "trust": 63,
    "fatigue": 49,
    "engagement": 58,
    "risk": "low",
    "ambassadors": 1,
    "tags": [
      "기본 모니터링"
    ],
    "recommendation": "CISO본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > CISO본부",
    "status": "active",
    "sortOrder": 4
  },
  {
    "id": "INFO_SECURITY",
    "name": "정보보안팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CISO",
    "members": 0,
    "readiness": 54,
    "trust": 72,
    "fatigue": 57,
    "engagement": 56,
    "risk": "medium",
    "ambassadors": 0,
    "tags": [
      "신뢰 안정",
      "리더 정보 확인 필요"
    ],
    "recommendation": "정보보안팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > DT부문 > CISO본부 > 정보보안팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "CX_INTEGRATION",
    "name": "고객경험통합팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "OPERATION",
    "members": 0,
    "readiness": 71,
    "trust": 59,
    "fatigue": 45,
    "engagement": 62,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "고객경험통합팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Operation본부 > 고객경험통합팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "CX_MANAGEMENT",
    "name": "고객경험관리팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "OPERATION",
    "members": 0,
    "readiness": 73,
    "trust": 58,
    "fatigue": 63,
    "engagement": 56,
    "risk": "medium",
    "ambassadors": 3,
    "tags": [
      "변화 수용 높음",
      "리더 정보 확인 필요"
    ],
    "recommendation": "고객경험관리팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Operation본부 > 고객경험관리팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "CUSTOMER_SERVICE_INNOVATION",
    "name": "고객서비스혁신팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "OPERATION",
    "members": 0,
    "readiness": 76,
    "trust": 56,
    "fatigue": 52,
    "engagement": 60,
    "risk": "medium",
    "ambassadors": 3,
    "tags": [
      "변화 수용 높음",
      "리더 정보 확인 필요"
    ],
    "recommendation": "고객서비스혁신팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Operation본부 > 고객서비스혁신팀",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "CLAIM",
    "name": "Claim팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "OPERATION",
    "members": 0,
    "readiness": 59,
    "trust": 52,
    "fatigue": 58,
    "engagement": 51,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "Claim팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Operation본부 > Claim팀",
    "status": "active",
    "sortOrder": 4
  },
  {
    "id": "SIU",
    "name": "SIU팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "OPERATION",
    "members": 0,
    "readiness": 68,
    "trust": 52,
    "fatigue": 71,
    "engagement": 50,
    "risk": "high",
    "ambassadors": 2,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "SIU팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Operation본부 > SIU팀",
    "status": "active",
    "sortOrder": 5
  },
  {
    "id": "FINANCE_MGMT",
    "name": "재무관리본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "김형남",
    "leaderTitle": "상무",
    "parentId": "FINANCE",
    "members": 2,
    "readiness": 65,
    "trust": 53,
    "fatigue": 64,
    "engagement": 51,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "기본 모니터링"
    ],
    "recommendation": "재무관리본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Finance부문 > 재무관리본부",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "ASSUMPTION_MGMT",
    "name": "가정관리팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "FINANCE_MGMT",
    "members": 0,
    "readiness": 60,
    "trust": 66,
    "fatigue": 54,
    "engagement": 57,
    "risk": "low",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "가정관리팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Finance부문 > 재무관리본부 > 가정관리팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "FINANCE_MGMT_TEAM",
    "name": "재무관리팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "FINANCE_MGMT",
    "members": 0,
    "readiness": 61,
    "trust": 71,
    "fatigue": 64,
    "engagement": 56,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "신뢰 안정",
      "리더 정보 확인 필요"
    ],
    "recommendation": "재무관리팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Finance부문 > 재무관리본부 > 재무관리팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "INVESTMENT",
    "name": "투자본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "신상욱",
    "leaderTitle": "상무",
    "parentId": "FINANCE",
    "members": 2,
    "readiness": 56,
    "trust": 74,
    "fatigue": 68,
    "engagement": 54,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "신뢰 안정",
      "피로도 관찰"
    ],
    "recommendation": "투자본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Finance부문 > 투자본부",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "FUND_MGMT",
    "name": "자금관리팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "INVESTMENT",
    "members": 0,
    "readiness": 62,
    "trust": 58,
    "fatigue": 48,
    "engagement": 57,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "자금관리팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Finance부문 > 투자본부 > 자금관리팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "INVESTMENT_STRATEGY",
    "name": "투자전략팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "INVESTMENT",
    "members": 0,
    "readiness": 63,
    "trust": 62,
    "fatigue": 69,
    "engagement": 52,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "투자전략팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > Finance부문 > 투자본부 > 투자전략팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "FACE_SALES_SUPPORT",
    "name": "대면영업지원본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "임지만",
    "leaderTitle": "이사",
    "parentId": "FACE_SALES",
    "members": 4,
    "readiness": 76,
    "trust": 63,
    "fatigue": 54,
    "engagement": 62,
    "risk": "low",
    "ambassadors": 4,
    "tags": [
      "조직 연결 허브",
      "변화 수용 높음"
    ],
    "recommendation": "대면영업지원본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > 대면영업지원본부",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "FACE_SALES_PLANNING",
    "name": "대면영업기획팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "FACE_SALES_SUPPORT",
    "members": 0,
    "readiness": 51,
    "trust": 64,
    "fatigue": 64,
    "engagement": 50,
    "risk": "medium",
    "ambassadors": 0,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "대면영업기획팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > 대면영업지원본부 > 대면영업기획팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "FACE_SALES_SUPPORT_TEAM",
    "name": "대면영업지원팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "FACE_SALES_SUPPORT",
    "members": 0,
    "readiness": 60,
    "trust": 69,
    "fatigue": 58,
    "engagement": 57,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "대면영업지원팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > 대면영업지원본부 > 대면영업지원팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "FACE_SALES_TRAINING",
    "name": "대면영업교육팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "FACE_SALES_SUPPORT",
    "members": 0,
    "readiness": 62,
    "trust": 52,
    "fatigue": 69,
    "engagement": 48,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "대면영업교육팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > 대면영업지원본부 > 대면영업교육팀",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "NEW_CHANNEL_PROMOTION",
    "name": "신채널추진팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "FACE_SALES_SUPPORT",
    "members": 0,
    "readiness": 66,
    "trust": 61,
    "fatigue": 73,
    "engagement": 51,
    "risk": "high",
    "ambassadors": 2,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "신채널추진팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > 대면영업지원본부 > 신채널추진팀",
    "status": "active",
    "sortOrder": 4
  },
  {
    "id": "GA_SALES",
    "name": "GA영업본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "안창모",
    "leaderTitle": "이사",
    "parentId": "FACE_SALES",
    "members": 7,
    "readiness": 67,
    "trust": 51,
    "fatigue": 44,
    "engagement": 58,
    "risk": "high",
    "ambassadors": 3,
    "tags": [
      "조직 연결 허브"
    ],
    "recommendation": "GA영업본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > GA영업본부",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "GA1_SALES",
    "name": "GA1영업팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "GA_SALES",
    "members": 0,
    "readiness": 51,
    "trust": 73,
    "fatigue": 52,
    "engagement": 57,
    "risk": "medium",
    "ambassadors": 0,
    "tags": [
      "신뢰 안정",
      "리더 정보 확인 필요"
    ],
    "recommendation": "GA1영업팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > GA영업본부 > GA1영업팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "GA2_SALES",
    "name": "GA2영업팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "GA_SALES",
    "members": 0,
    "readiness": 56,
    "trust": 50,
    "fatigue": 52,
    "engagement": 51,
    "risk": "high",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "GA2영업팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > GA영업본부 > GA2영업팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "GA3_SALES",
    "name": "GA3영업팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "GA_SALES",
    "members": 0,
    "readiness": 61,
    "trust": 51,
    "fatigue": 53,
    "engagement": 53,
    "risk": "high",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "GA3영업팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > GA영업본부 > GA3영업팀",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "GA4_SALES",
    "name": "GA4영업팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "GA_SALES",
    "members": 0,
    "readiness": 66,
    "trust": 52,
    "fatigue": 53,
    "engagement": 55,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "GA4영업팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > GA영업본부 > GA4영업팀",
    "status": "active",
    "sortOrder": 4
  },
  {
    "id": "GA5_SALES",
    "name": "GA5영업팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "GA_SALES",
    "members": 0,
    "readiness": 71,
    "trust": 53,
    "fatigue": 53,
    "engagement": 57,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "GA5영업팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > GA영업본부 > GA5영업팀",
    "status": "active",
    "sortOrder": 5
  },
  {
    "id": "GA6_SALES",
    "name": "GA6영업팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "GA_SALES",
    "members": 0,
    "readiness": 51,
    "trust": 54,
    "fatigue": 54,
    "engagement": 50,
    "risk": "medium",
    "ambassadors": 0,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "GA6영업팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > GA영업본부 > GA6영업팀",
    "status": "active",
    "sortOrder": 6
  },
  {
    "id": "GA7_SALES",
    "name": "GA7영업팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "GA_SALES",
    "members": 0,
    "readiness": 56,
    "trust": 55,
    "fatigue": 54,
    "engagement": 52,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "GA7영업팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > GA영업본부 > GA7영업팀",
    "status": "active",
    "sortOrder": 7
  },
  {
    "id": "BA_SALES",
    "name": "BA영업팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "FACE_SALES",
    "members": 0,
    "readiness": 72,
    "trust": 72,
    "fatigue": 72,
    "engagement": 57,
    "risk": "high",
    "ambassadors": 2,
    "tags": [
      "변화 수용 높음",
      "신뢰 안정",
      "피로도 관찰"
    ],
    "recommendation": "BA영업팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대면영업부문 > BA영업팀",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "HR_SUPPORT",
    "name": "인사지원본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "김대현",
    "leaderTitle": "이사",
    "parentId": "HR",
    "members": 2,
    "readiness": 76,
    "trust": 61,
    "fatigue": 65,
    "engagement": 57,
    "risk": "medium",
    "ambassadors": 3,
    "tags": [
      "변화 수용 높음"
    ],
    "recommendation": "인사지원본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 인사관리부문 > 인사지원본부",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "EHS_GA",
    "name": "EHS&GA팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "HR_SUPPORT",
    "members": 0,
    "readiness": 72,
    "trust": 69,
    "fatigue": 64,
    "engagement": 59,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "변화 수용 높음",
      "리더 정보 확인 필요"
    ],
    "recommendation": "EHS&GA팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 인사관리부문 > 인사지원본부 > EHS&GA팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "EXECUTIVE_SUPPORT",
    "name": "Executive Support팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "HR_SUPPORT",
    "members": 0,
    "readiness": 53,
    "trust": 56,
    "fatigue": 74,
    "engagement": 45,
    "risk": "high",
    "ambassadors": 0,
    "tags": [
      "피로도 관찰",
      "리더 정보 확인 필요"
    ],
    "recommendation": "Executive Support팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 인사관리부문 > 인사지원본부 > Executive Support팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "PEOPLE_EXPERIENCE",
    "name": "People Experience팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "HR",
    "members": 0,
    "readiness": 62,
    "trust": 74,
    "fatigue": 59,
    "engagement": 59,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "신뢰 안정",
      "리더 정보 확인 필요"
    ],
    "recommendation": "People Experience팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 인사관리부문 > People Experience팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "TALENT_DEVELOPMENT",
    "name": "Talent Development팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "HR",
    "members": 0,
    "readiness": 66,
    "trust": 56,
    "fatigue": 57,
    "engagement": 55,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "Talent Development팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 인사관리부문 > Talent Development팀",
    "status": "active",
    "sortOrder": 3
  },
  {
    "id": "HR_OTHERS",
    "name": "HR others",
    "level": "team",
    "orgType": "기타조직",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "HR",
    "members": 0,
    "readiness": 63,
    "trust": 69,
    "fatigue": 49,
    "engagement": 61,
    "risk": "low",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요",
      "특수 조직"
    ],
    "recommendation": "HR others은 업로드된 조직 마스터 기준의 기타조직 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 인사관리부문 > HR others",
    "status": "active",
    "sortOrder": 4
  },
  {
    "id": "LEGAL_PRIVACY",
    "name": "법무&프라이버시본부",
    "level": "hq",
    "orgType": "본부",
    "orgDepth": 2,
    "leader": "이슬이",
    "leaderTitle": "이사",
    "parentId": "LEGAL_COMPLIANCE",
    "members": 1,
    "readiness": 62,
    "trust": 57,
    "fatigue": 55,
    "engagement": 55,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "기본 모니터링"
    ],
    "recommendation": "법무&프라이버시본부은 업로드된 조직 마스터 기준의 본부 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 법무&준법감시부문 > 법무&프라이버시본부",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "LEGAL_PRIVACY_TEAM",
    "name": "법무&프라이버시팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 3,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "LEGAL_PRIVACY",
    "members": 0,
    "readiness": 74,
    "trust": 57,
    "fatigue": 61,
    "engagement": 57,
    "risk": "medium",
    "ambassadors": 3,
    "tags": [
      "변화 수용 높음",
      "리더 정보 확인 필요"
    ],
    "recommendation": "법무&프라이버시팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 법무&준법감시부문 > 법무&프라이버시본부 > 법무&프라이버시팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "COMPLIANCE_TEAM",
    "name": "준법감시팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "LEGAL_COMPLIANCE",
    "members": 0,
    "readiness": 75,
    "trust": 63,
    "fatigue": 44,
    "engagement": 65,
    "risk": "low",
    "ambassadors": 3,
    "tags": [
      "변화 수용 높음",
      "리더 정보 확인 필요"
    ],
    "recommendation": "준법감시팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 법무&준법감시부문 > 준법감시팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "AUDIT_TEAM",
    "name": "감사팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "AUDIT_EXECUTIVE",
    "members": 0,
    "readiness": 73,
    "trust": 72,
    "fatigue": 56,
    "engagement": 63,
    "risk": "low",
    "ambassadors": 3,
    "tags": [
      "변화 수용 높음",
      "신뢰 안정",
      "리더 정보 확인 필요"
    ],
    "recommendation": "감사팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 최고감사책임자 > 감사팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "RISK_MANAGEMENT",
    "name": "리스크관리팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "RM",
    "members": 0,
    "readiness": 54,
    "trust": 55,
    "fatigue": 51,
    "engagement": 53,
    "risk": "medium",
    "ambassadors": 0,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "리스크관리팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > RM본부 > 리스크관리팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "RISK_ASSESSMENT",
    "name": "리스크평가팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "RM",
    "members": 0,
    "readiness": 65,
    "trust": 56,
    "fatigue": 65,
    "engagement": 52,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "리스크평가팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > RM본부 > 리스크평가팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "EXTERNAL_COOPERATION_TEAM",
    "name": "대외협력팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "EXTERNAL_COOPERATION",
    "members": 0,
    "readiness": 64,
    "trust": 73,
    "fatigue": 62,
    "engagement": 58,
    "risk": "medium",
    "ambassadors": 2,
    "tags": [
      "신뢰 안정",
      "리더 정보 확인 필요"
    ],
    "recommendation": "대외협력팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 대외협력본부 > 대외협력팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "CONSUMER_PROTECTION_POLICY",
    "name": "소비자보호정책팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CONSUMER_PROTECTION",
    "members": 0,
    "readiness": 56,
    "trust": 70,
    "fatigue": 53,
    "engagement": 58,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "신뢰 안정",
      "리더 정보 확인 필요"
    ],
    "recommendation": "소비자보호정책팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 소비자보호본부 > 소비자보호정책팀",
    "status": "active",
    "sortOrder": 1
  },
  {
    "id": "CONSUMER_COMPLAINT",
    "name": "소비자보호민원팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CONSUMER_PROTECTION",
    "members": 0,
    "readiness": 60,
    "trust": 60,
    "fatigue": 59,
    "engagement": 54,
    "risk": "medium",
    "ambassadors": 1,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "소비자보호민원팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 소비자보호본부 > 소비자보호민원팀",
    "status": "active",
    "sortOrder": 2
  },
  {
    "id": "QUALITY_MONITORING",
    "name": "품질모니터링팀",
    "level": "team",
    "orgType": "팀",
    "orgDepth": 2,
    "leader": "리더 미정",
    "leaderTitle": "",
    "parentId": "CONSUMER_PROTECTION",
    "members": 0,
    "readiness": 65,
    "trust": 63,
    "fatigue": 52,
    "engagement": 59,
    "risk": "low",
    "ambassadors": 2,
    "tags": [
      "리더 정보 확인 필요"
    ],
    "recommendation": "품질모니터링팀은 업로드된 조직 마스터 기준의 팀 조직입니다. 리더/구성원 이동과 문화 신호를 실제 운영 데이터로 업데이트하세요.",
    "sourcePath": "CEO > 소비자보호본부 > 품질모니터링팀",
    "status": "active",
    "sortOrder": 3
  }
];

window.LINA_ORG_PEOPLE = [
  {
    "id": "person-STRATEGY-박경식-1",
    "name": "박경식",
    "role": "경영전략부문 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "STRATEGY",
    "influence": 72,
    "readiness": 73,
    "title": "전무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-DIGITAL-이진호-2",
    "name": "이진호",
    "role": "Digital부문 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "DIGITAL",
    "influence": 73,
    "readiness": 67,
    "title": "부사장",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-DT-김호섭-3",
    "name": "김호섭",
    "role": "DT부문 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "DT",
    "influence": 84,
    "readiness": 69,
    "title": "부사장",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-OPERATION-허혁-4",
    "name": "허혁",
    "role": "Operation본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "OPERATION",
    "influence": 91,
    "readiness": 83,
    "title": "이사",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-FACE_SALES-이장록-5",
    "name": "이장록",
    "role": "대면영업부문 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "FACE_SALES",
    "influence": 72,
    "readiness": 83,
    "title": "전무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-HR-박규현-6",
    "name": "박규현",
    "role": "인사관리부문 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "HR",
    "influence": 87,
    "readiness": 83,
    "title": "전무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-LEGAL_COMPLIANCE-이재현-7",
    "name": "이재현",
    "role": "법무&준법감시부문 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "LEGAL_COMPLIANCE",
    "influence": 81,
    "readiness": 62,
    "title": "전무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-AUDIT_EXECUTIVE-채명균-8",
    "name": "채명균",
    "role": "최고감사책임자 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "AUDIT_EXECUTIVE",
    "influence": 79,
    "readiness": 83,
    "title": "전무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-RM-오수연-9",
    "name": "오수연",
    "role": "RM본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "RM",
    "influence": 86,
    "readiness": 63,
    "title": "상무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-EXTERNAL_COOPERATION-김기성-10",
    "name": "김기성",
    "role": "대외협력본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "EXTERNAL_COOPERATION",
    "influence": 74,
    "readiness": 81,
    "title": "부사장",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-CONSUMER_PROTECTION-서민호-11",
    "name": "서민호",
    "role": "소비자보호본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "CONSUMER_PROTECTION",
    "influence": 89,
    "readiness": 66,
    "title": "상무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-STRATEGY_MGMT-임승관-12",
    "name": "임승관",
    "role": "경영관리본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "STRATEGY_MGMT",
    "influence": 80,
    "readiness": 68,
    "title": "이사",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-CUSTOMER_SOLUTION-도기철-13",
    "name": "도기철",
    "role": "고객솔루션본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "CUSTOMER_SOLUTION",
    "influence": 79,
    "readiness": 76,
    "title": "이사",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-CHANNEL_STRATEGY-최상혁-14",
    "name": "최상혁",
    "role": "채널전략본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "CHANNEL_STRATEGY",
    "influence": 81,
    "readiness": 81,
    "title": "이사",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-DATA_CONTROL-오인정-15",
    "name": "오인정",
    "role": "Data Control본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "DATA_CONTROL",
    "influence": 77,
    "readiness": 89,
    "title": "이사",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-DIGITAL_SALES-장재원-16",
    "name": "장재원",
    "role": "Digital Sales본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "DIGITAL_SALES",
    "influence": 84,
    "readiness": 73,
    "title": "상무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-DIGITAL_SERVICE-박기홍-17",
    "name": "박기홍",
    "role": "Digital Service본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "DIGITAL_SERVICE",
    "influence": 83,
    "readiness": 63,
    "title": "상무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-INSURANCE_DEV-김현우-18",
    "name": "김현우",
    "role": "보험개발본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "INSURANCE_DEV",
    "influence": 77,
    "readiness": 78,
    "title": "상무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-SALES_DEV-송유종-19",
    "name": "송유종",
    "role": "Sales개발본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "SALES_DEV",
    "influence": 83,
    "readiness": 62,
    "title": "이사",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-INFRA_SERVICE-서용식-20",
    "name": "서용식",
    "role": "인프라서비스본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "INFRA_SERVICE",
    "influence": 78,
    "readiness": 85,
    "title": "상무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-CISO-조용현-21",
    "name": "조용현",
    "role": "CISO본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "CISO",
    "influence": 76,
    "readiness": 70,
    "title": "상무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-FINANCE_MGMT-김형남-22",
    "name": "김형남",
    "role": "재무관리본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "FINANCE_MGMT",
    "influence": 77,
    "readiness": 81,
    "title": "상무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-INVESTMENT-신상욱-23",
    "name": "신상욱",
    "role": "투자본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "INVESTMENT",
    "influence": 87,
    "readiness": 77,
    "title": "상무",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-FACE_SALES_SUPPORT-임지만-24",
    "name": "임지만",
    "role": "대면영업지원본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "FACE_SALES_SUPPORT",
    "influence": 78,
    "readiness": 74,
    "title": "이사",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-GA_SALES-안창모-25",
    "name": "안창모",
    "role": "GA영업본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "GA_SALES",
    "influence": 83,
    "readiness": 86,
    "title": "이사",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-HR_SUPPORT-김대현-26",
    "name": "김대현",
    "role": "인사지원본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "HR_SUPPORT",
    "influence": 72,
    "readiness": 72,
    "title": "이사",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-LEGAL_PRIVACY-이슬이-27",
    "name": "이슬이",
    "role": "법무&프라이버시본부 조직장/표시 리더",
    "position": "리더",
    "generation": "40대",
    "unitId": "LEGAL_PRIVACY",
    "influence": 75,
    "readiness": 68,
    "title": "이사",
    "tags": [
      "조직장",
      "표시 리더"
    ]
  },
  {
    "id": "person-STRATEGY-서연주-28",
    "name": "서연주",
    "role": "경영전략부문 주요 담당자/표시 인물",
    "position": "리더",
    "generation": "40대",
    "unitId": "STRATEGY",
    "influence": 71,
    "readiness": 70,
    "title": "이사",
    "tags": [
      "주요 담당자"
    ]
  },
  {
    "id": "person-CUSTOMER_SOLUTION-안병덕-29",
    "name": "안병덕",
    "role": "고객솔루션본부 주요 담당자/표시 인물",
    "position": "리더",
    "generation": "40대",
    "unitId": "CUSTOMER_SOLUTION",
    "influence": 88,
    "readiness": 70,
    "title": "부장",
    "tags": [
      "주요 담당자"
    ]
  },
  {
    "id": "person-CUSTOMER_SOLUTION-김권수-30",
    "name": "김권수",
    "role": "고객솔루션본부 주요 담당자/표시 인물",
    "position": "리더",
    "generation": "40대",
    "unitId": "CUSTOMER_SOLUTION",
    "influence": 74,
    "readiness": 82,
    "title": "차장",
    "tags": [
      "주요 담당자"
    ]
  },
  {
    "id": "person-HR-김민정-31",
    "name": "김민정",
    "role": "인사관리부문 주요 담당자/표시 인물",
    "position": "리더",
    "generation": "40대",
    "unitId": "HR",
    "influence": 74,
    "readiness": 74,
    "title": "부장",
    "tags": [
      "주요 담당자"
    ]
  },
  {
    "id": "person-HR-노동욱-32",
    "name": "노동욱",
    "role": "인사관리부문 주요 담당자/표시 인물",
    "position": "리더",
    "generation": "40대",
    "unitId": "HR",
    "influence": 84,
    "readiness": 66,
    "title": "부장",
    "tags": [
      "주요 담당자"
    ]
  }
];
